AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  presto-step-functions

  Sample SAM Template for presto-step-functions

Resources:
  PrestoCarChargeWorkflow:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/presto-charge-workflow.asl.json
      DefinitionSubstitutions:
        StartChargeArn: !GetAtt StartCharge.Arn
        PollChargeArn: !GetAtt PollCharge.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref StartCharge
        - LambdaInvokePolicy:
            FunctionName: !Ref PollCharge

  StartCharge:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/start_charge/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64

  PollCharge:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/poll_charge/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64

Outputs:
 # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
 # Find out more about other implicit resources you can reference within SAM
 # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
 PrestoCarChargeWorkflowArn:
   Description: "Stock Trading State machine ARN"
   Value: !Ref PrestoCarChargeWorkflow
 PrestoCarChargeWorkflowRoleArn:
   Description: "IAM Role created for Stock Trading State machine based on the specified SAM Policy Templates"
   Value: !GetAtt PrestoCarChargeWorkflowRole.Arn
